### ISSUE TITLE
TypeScript compilation error after install

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [GNURub/ngx-daterangepicker#1]
Hi

After the npm install and module import in the build i have the following error:

ERROR in .../node_modules/ngx-daterangepicker/src/ngx-daterangepicker/index.ts
Module build failed: Error: ...\node_modules\ngx-daterangepicker\src\ngx-daterangepicker\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv). at AngularCompilerPlugin.getCompiledFile (...\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
 at plugin.done.then (...\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**In the npm the version number is 1.0.1 and here the version number is 1.5.0**

**Comment by morphik** [comment]
Just add this missing file to the `files` section in `tsconfig`.
```
"files": [
    "../node_modules/ngx-daterangepicker/src/ngx-daterangepicker/index.ts"
]
```

That should do the trick.

**Comment by anuj509** [comment]
@morphik this error is coming after i added it in tsconfig.app.json as "files".
please let me know the workaround for this issue.

**Comment by beyondtheobservableuniverse** [comment]
@morphik After add index.ts in tsconfig.ts

I have another error:
ERROR in No NgModule metadata found for 'AppModule'.

**Comment by GNURub** [comment]
npm i ngx-daterangepicker@^2.0.0

**Comment by beyondtheobservableuniverse** [comment]
Thank you very much!
